name: formatting
on:
  push:
    paths-ignore:
      - ".github/**"
      - "*.md"
    branches: ["main"]

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --config-path=stylua.toml lua/
